package com.myhindlab.abkat.models;

import java.io.Serializable;
import java.util.List;

public class BreastScreeningDistrictWiseModel implements Serializable {


    /**
     * status : Success
     * message : Breast Screening Details
     * output : [{"DISTLGDCODE":466,"DISTNAME":"AHMEDNAGAR","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":467,"DISTNAME":"AKOLA","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":468,"DISTNAME":"AMRAVATI","TOTAL_PATIENTS":5,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":5},{"DISTLGDCODE":469,"DISTNAME":"AURANGABAD","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":470,"DISTNAME":"BEED","TOTAL_PATIENTS":2,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":2},{"DISTLGDCODE":471,"DISTNAME":"BHANDARA","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":472,"DISTNAME":"BULDHANA","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":473,"DISTNAME":"CHANDRAPUR","TOTAL_PATIENTS":1,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":1},{"DISTLGDCODE":474,"DISTNAME":"DHULE","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":475,"DISTNAME":"GADCHIROLI","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":476,"DISTNAME":"GONDIA","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":477,"DISTNAME":"HINGOLI","TOTAL_PATIENTS":987,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":987},{"DISTLGDCODE":478,"DISTNAME":"JALGAON","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":479,"DISTNAME":"JALNA","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":480,"DISTNAME":"KOLHAPUR","TOTAL_PATIENTS":1,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":1},{"DISTLGDCODE":481,"DISTNAME":"LATUR","TOTAL_PATIENTS":58,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":58},{"DISTLGDCODE":482,"DISTNAME":"MUMBAI CITY","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":483,"DISTNAME":"MUMBAI SUBURBAN EAST","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":999,"DISTNAME":"MUMBAI SUBURBAN WEST","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":484,"DISTNAME":"NAGPUR","TOTAL_PATIENTS":63,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":63},{"DISTLGDCODE":485,"DISTNAME":"NANDED","TOTAL_PATIENTS":167,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":167},{"DISTLGDCODE":486,"DISTNAME":"NANDURBAR","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":487,"DISTNAME":"Nashik","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":488,"DISTNAME":"OSMANABAD","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":665,"DISTNAME":"PALGHAR","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":489,"DISTNAME":"PARBHANI","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":490,"DISTNAME":"PUNE","TOTAL_PATIENTS":1,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":1},{"DISTLGDCODE":491,"DISTNAME":"RAIGAD","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":492,"DISTNAME":"RATNAGIRI","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":493,"DISTNAME":"SANGLI","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":494,"DISTNAME":"SATARA","TOTAL_PATIENTS":134,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":134},{"DISTLGDCODE":495,"DISTNAME":"SINDHUDURG","TOTAL_PATIENTS":67,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":67},{"DISTLGDCODE":496,"DISTNAME":"SOLAPUR","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":497,"DISTNAME":"THANE","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":498,"DISTNAME":"WARDHA","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0},{"DISTLGDCODE":499,"DISTNAME":"WASHIM","TOTAL_PATIENTS":3,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":3},{"DISTLGDCODE":500,"DISTNAME":"YAVATMAL","TOTAL_PATIENTS":0,"POSITIVE_PATIENTS":0,"NEGATIVE_PATIENTS":0,"NO_STATUS_PATIENTS":0}]
     */

    private String status;
    private String message;
    private List<OutputBean> output;

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public List<OutputBean> getOutput() {
        return output;
    }

    public void setOutput(List<OutputBean> output) {
        this.output = output;
    }

    public static class OutputBean implements Serializable {
        /**
         * DISTLGDCODE : 466
         * DISTNAME : AHMEDNAGAR
         * TOTAL_PATIENTS : 0
         * POSITIVE_PATIENTS : 0
         * NEGATIVE_PATIENTS : 0
         * NO_STATUS_PATIENTS : 0
         */

        private int DISTLGDCODE;
        private String DISTNAME;
        private int TOTAL_PATIENTS;
        private int POSITIVE_PATIENTS;
        private int NEGATIVE_PATIENTS;
        private int NO_STATUS_PATIENTS;

        public int getDISTLGDCODE() {
            return DISTLGDCODE;
        }

        public void setDISTLGDCODE(int DISTLGDCODE) {
            this.DISTLGDCODE = DISTLGDCODE;
        }

        public String getDISTNAME() {
            return DISTNAME;
        }

        public void setDISTNAME(String DISTNAME) {
            this.DISTNAME = DISTNAME;
        }

        public int getTOTAL_PATIENTS() {
            return TOTAL_PATIENTS;
        }

        public void setTOTAL_PATIENTS(int TOTAL_PATIENTS) {
            this.TOTAL_PATIENTS = TOTAL_PATIENTS;
        }

        public int getPOSITIVE_PATIENTS() {
            return POSITIVE_PATIENTS;
        }

        public void setPOSITIVE_PATIENTS(int POSITIVE_PATIENTS) {
            this.POSITIVE_PATIENTS = POSITIVE_PATIENTS;
        }

        public int getNEGATIVE_PATIENTS() {
            return NEGATIVE_PATIENTS;
        }

        public void setNEGATIVE_PATIENTS(int NEGATIVE_PATIENTS) {
            this.NEGATIVE_PATIENTS = NEGATIVE_PATIENTS;
        }

        public int getNO_STATUS_PATIENTS() {
            return NO_STATUS_PATIENTS;
        }

        public void setNO_STATUS_PATIENTS(int NO_STATUS_PATIENTS) {
            this.NO_STATUS_PATIENTS = NO_STATUS_PATIENTS;
        }
    }
}
