// ignore_for_file: file_names, constant_identifier_names

enum DashboardMenu {
  PatientRegistration,
  CampCalendar,
  D2DTeams,
  DailyWorkDashboard,
  LiverScanning,
  S2TPatientApp,
  CallingList,
  UserAttendance,
  HealthScreeningDetails,
  // CampAwarenessActivity,
  Acknowledgement,
  ELearning,
  OtherMenu,
  FingerPrintUpload,
  DeviceAndResourceMapping,
  ResourceReMapping,
  CampApproval,
  CampCreation,
  ExpenseClaim,
  CampReadinessForm,
  PacketAllocation,
  PacketCollection,
  CTAssignment,
  PacketReceive,
  D2DTeam,
  TeamCampMapping,
  AppointmentConfirmedList,
  CommonBeneficiaryList,
  D2DCampActivity,
  AppointmentAndSampleCollectionOfCT,
  D2DAvailabilityScreening,
  // D2DHealthScreening,
  D2DPhysicalExaminationDetails,
  PaymentAndInvoice,
  MedicineDeliveryMenu,
  MedicineReturn,
  MedicineDelivery,
  PickupMedicinePacket,
  // AnalyticalDashboard,
}

enum DropDownTypeMenu {
  CampType,
  InitiatedBy,
  TalukaCampList,
  LandingLabCampCreation,
  CampID,
  ExpenseHead,
  SubExpenseHead,
  SubOrganization,
  BindDivision,
  BindDistrict,
  BindLab,
  CampTypeAndCatagory,
  CampReadinessCampID,
  TestToReject,
  ReasonTest,
  CampDetailsTeam,
  AppointmentStatus,
  UserMappedTaluka,
  ReportDeliveryExecutive,
  CallStatus,
  CallingRemark,
  DailyWorkDashboardLab,
  RejectedStatus,
  SearchBy,
  Years,
  Months,
  PaidByCompany,
  AllDistrictListForPhyExam,
  District,
  StatusRemark,
  SelectExecutive,
  TalukaPacketRecive,
  TeamCampLab,
  SelectTeam,
  AssignResources,
}

enum DropDownMultipleTypeMenu {
  ScreeningTest,
  SubResource,
  CampID,
  UpdateSubResource,
}

enum HealthScreeningDetailsMenu {
  ScreeningStatus,
  CampClosing,
  PhysicalExamination,
  SampleCollection,
  BasicHealthInfo,
  D2DPhysicalExamination,
  LungFunctionTest,
  AudioScreeningTest,
  VisualScreeningTest,
}

enum APIMode { Live, Beta }
