apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'

android {
    namespace "com.myhindlab.abkat"

    defaultConfig {
        applicationId "in.janarogyaseva.s2t_operational"
        ndkVersion "28.0.13004108"
        minSdkVersion 26
        targetSdkVersion 36
        compileSdk 36
        versionCode 97
        versionName "8.12"
        android.buildFeatures.buildConfig true

        multiDexEnabled true
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        ndk.abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'

        aaptOptions {
            noCompress 'txt', 'json' // Add file types if needed
        }

    }


    Properties properties = new Properties()
    properties.load(project.rootProject.file("local.properties").newDataInputStream())


    flavorDimensions "version"
    productFlavors{
        beta{
            dimension "version"
            applicationId "in.janarogyaseva.s2t_operational.beta"
            versionCode 96
            versionName "9.82"
            multiDexEnabled true
            testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

//            ndk.abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
//            manifestPlaceholders = [appLabel:"@string/app_name_beta"]

            resValue "string", "app_name", "S2T-Operational-Beta"
            buildConfigField 'String', 'domain', '"https://testmcwwb.myhindlab.com/BETA_MYHINDLABDOCS"'
//            buildConfigField 'String', 'domain', '"https://newtesting.myhindlab.com/BETA_MYHINDLABDOCS"'
            buildConfigField 'String', 'baseURL', '"https://testmcwwb.myhindlab.com/webservices/"'
//            buildConfigField 'String', 'baseURL', '"https://newtesting.myhindlab.com/webservices/"'
            buildConfigField 'String', 'hllBaseURl', '"http://beta.hllconnect.in/webservice/hllconnect.asmx/"'
            buildConfigField 'String', 'mediProcsBaseURl', '"http://betaclient.cschealthcare.in/beta/MediprocsClient.asmx/"'
            buildConfigField 'String', 'reportMyhindlab', '"https://reports.myhindlab.com/ReportsMCWBETA/ABHABETA/"'

            buildConfigField 'String', 'CMID', '"@sbx"'
            buildConfigField 'String', 'HIPID', '"IN2710003086"'
            buildConfigField 'String', 'HIPName', '"Jan Arogya Seva"'

            buildConfigField 'String', 'BENEFIT_NAME', '"HSCC"'

            buildConfigField 'String', 'ClientID', "\"${properties.getProperty("ABDM_ID")}\""
            buildConfigField 'String', 'SecretId', "\"${properties.getProperty("ABDM_KEY")}\""
            manifestPlaceholders = [MAP_API_KEY: "\"${properties.getProperty("MAP_API_KEY")}\""]

            buildConfigField 'String', 'ABHA', '"https://dev.abdm.gov.in/"'
            buildConfigField 'String', 'HealthIDSBX', '"https://abhasbx.abdm.gov.in/abha/api/v3/"'
            buildConfigField 'String', 'PHRSBX', '"https://phrsbx.abdm.gov.in/api/"'

            buildConfigField 'String', 'ABHAAPI', '"https://apis.abdm.gov.in/"'
            buildConfigField 'String', 'DISHAAPI', '"http://103.251.94.38:8080/DISHA_API/"'


            buildConfigField "boolean", "isBeta", "true"
        }

        live{
            dimension "version"
            applicationId "in.janarogyaseva.s2t_operational"
            versionCode 26
            versionName "9.82"
            multiDexEnabled true
            testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

//            ndk.abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
//            manifestPlaceholders = [appLabel:"@string/app_name_live"]

            resValue "string", "app_name", "S2T-Operational"
            buildConfigField 'String', 'domain', '"https://mcwwb.janarogyaseva.in/MCWWBDOCS_LIVE"'
//            buildConfigField 'String', 'baseURL', '"https://facedetection.cschealthcare.in/webservices/"'
            buildConfigField 'String', 'baseURL', '"https://mcwwb.janarogyaseva.in/webservices/"'
            buildConfigField 'String', 'hllBaseURl', '"https://erp.hllconnect.in/webservice/hllconnect.asmx/"'
            buildConfigField 'String', 'mediProcsBaseURl', '"http://betaclient.cschealthcare.in/beta/MediprocsClient.asmx/"'
//            buildConfigField 'String', 'reportMyhindlab', '"https://reports.myhindlab.com/ReportsMCWBETA/ABHABETA/"'
            buildConfigField 'String', 'reportMyhindlab', '"http://reports.myhindlab.com/ReportsMCWLive/ABHA/"'

            buildConfigField 'String', 'CMID', '"@abdm"'
            buildConfigField 'String', 'HIPID', '"IN2710053234"'
            buildConfigField 'String', 'HIPName', '"Jan Arogya Seva"'
            buildConfigField 'String', 'BENEFIT_NAME', '"HSCC"'
            buildConfigField 'String', 'ClientID', "\"${properties.getProperty("ABDM_ID_LIVE")}\""
            buildConfigField 'String', 'SecretId', "\"${properties.getProperty("ABDM_KEY_LIVE")}\""
            manifestPlaceholders = [MAP_API_KEY: "\"${properties.getProperty("MAP_API_KEY")}\""]

            buildConfigField 'String', 'DISHAAPI', '"http://103.251.94.38:8080/DISHA_API/"'


            buildConfigField 'String', 'ABHAAPI', '"https://abha.abdm.gov.in/"'
//            buildConfigField 'String', 'ABHA', '"https://dev.abdm.gov.in/"'
            buildConfigField 'String', 'ABHA', '"https://abha.abdm.gov.in/api/abha/v3/"'
//            buildConfigField 'String', 'HealthIDSBX', '"https://abhasbx.abdm.gov.in/abha/api/v3/"'
            buildConfigField 'String', 'HealthIDSBX', '"https://healthid.abdm.gov.in/api/abha/v3/"'
//            buildConfigField 'String', 'PHRSBX', '"https://phrsbx.abdm.gov.in/api/"'
            buildConfigField 'String', 'PHRSBX', '"https://phr.abdm.gov.in/api/"'
            buildConfigField "boolean", "isBeta", "false"

//            buildConfigField 'String', 'baseURL', '"https://mcwwb.janarogyaseva.in/webservices/"'
         //   buildConfigField 'String', 'baseURL', '"https://mcwwb.myhindlab.com/webservices/"'
           // buildConfigField 'String', 'baseURL', '"http://mcwwb.tvetonline.in/webservices/"'




        }

    }

    signingConfigs {

        debug {

            storeFile file('debug.keystore')

            storePassword 'android'

            keyAlias 'androiddebugkey'

            keyPassword 'android'


        }

        release {

            storeFile file('HealthCheckupKeyStore.jks')

            storePassword 'Avante@123'

            keyAlias 'HelthCheckup'

            keyPassword 'Avante@123'

        }

    }

    buildTypes {

        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
//            multiDexKeepFile file('multidex-config.txt')
            buildConfigField ("String", "YOUTUBE_KEY", "\"AIzaSyDB-DrjjhTCreQ0dE0lxrW8A8yCSHBDfaY\"")
        }

        debug {
            signingConfig signingConfigs.debug
            buildConfigField ("String", "YOUTUBE_KEY", "\"AIzaSyDB-DrjjhTCreQ0dE0lxrW8A8yCSHBDfaY\"")
        }

    }

    compileOptions {
        sourceCompatibility = '17'
        targetCompatibility = '17'
    }



    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }

    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }

    packagingOptions {
        exclude 'META-INF/com.android.tools/proguard/coroutines.pro'
        exclude 'META-INF/kotlinx_coroutines_core.version'
    }

//    viewBinding{
//        enabled true
//    }


    buildFeatures {
        viewBinding true
        dataBinding true
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //noinspection GradleCompatible
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.annotation:annotation:1.6.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation files('libs\\jxl.jar')
    implementation 'androidx.navigation:navigation-fragment:2.5.3'
    implementation 'androidx.navigation:navigation-ui:2.5.3'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
//    implementation 'com.google.android.gms:play-services:12.0.1'
    implementation 'androidx.recyclerview:recyclerview:1.3.0'
    implementation 'com.google.android.gms:play-services-maps:18.2.0'
    implementation 'com.google.android.gms:play-services-location:21.0.1'
    implementation 'com.google.android.gms:play-services-places:17.1.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'com.squareup.okhttp3:okhttp:4.11.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'com.nineoldandroids:library:2.4.0'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.rengwuxian.materialedittext:library:2.1.4'
    implementation 'com.github.GrenderG:Toasty:1.4.2'
    implementation 'com.aurelhubert:ahbottomnavigation:2.1.0'
    implementation 'de.hdodenhof:circleimageview:3.0.0'
    implementation 'me.dm7.barcodescanner:zxing:1.9.8'
//    implementation 'com.theartofdev.edmodo:android-image-cropper:2.6.0'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.0.2'
    implementation 'com.ogaclejapan.smarttablayout:library:1.7.0@aar'
    implementation('com.github.gcacace:signature-pad:1.3.1') {
        exclude group: 'com.android.support'
        exclude module: 'appcompat-v7'
        exclude module: 'support-v4'
    }
    implementation files('libs/BOLT_V6_24.jar')
    //    implementation files('libs\\EZView-dex2jar.jar')
    //    implementation files('libs/FDxSDKProAndroid.jar')
    implementation(name: 'ycbtsdk-release', ext: 'aar')

    implementation files('libs/achartengine-1.0.0.jar')
    implementation files('libs/mantra.mfs100.jar')
    implementation files('libs/YouTubeAndroidPlayerApi.jar')
    implementation project(path: ':synclib')
//    implementation 'com.vincent.filepicker:MultiTypeFilePicker:1.0.8'
    implementation 'com.github.TutorialsAndroid:FilePicker:v7.0.19'

//    implementation group: 'org.apache.poi', name: 'poi-ooxml', version: '5.2.3'

    implementation "androidx.work:work-runtime:2.8.1"


    implementation 'com.github.bumptech.glide:glide:4.16.0'


//    implementation 'com.google.android.play:core:1.10.3'

    implementation 'no.nordicsemi.android:ble:2.6.0-alpha03'
    implementation("androidx.viewpager2:viewpager2:1.0.0")


    //Get SafeySDK
    implementation files('./libs/SafeySDK.aar')
    implementation 'com.github.ybq:Android-SpinKit:1.4.0'
    implementation 'com.intuit.sdp:sdp-android:1.0.6'
    implementation 'com.intuit.ssp:ssp-android:1.0.6'
    implementation 'com.github.GoodieBag:Pinview:v1.4'


    implementation("com.vanniktech:android-image-cropper:4.6.0")

    implementation 'com.github.tbruyelle:rxpermissions:2.x.v0.9.3'

    //PDF Create
    //PDF viewerMedi
    implementation 'com.itextpdf:itext7-core:7.1.13'
//    implementation 'com.github.barteksc:android-pdf-viewer:3.1.0-beta.1'

    implementation 'com.squareup.okhttp3:logging-interceptor:4.11.0'

//    $kotlin_version = "1.6.21"

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4"
    implementation 'androidx.core:core-ktx:1.10.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.10"
    implementation 'com.wdullaer:materialdatetimepicker:4.2.3'

    implementation project(':omronconnectivitylibrary')
    implementation project(':omronconnectivitylibraryassets')


//    ------Google places API-----

//    implementation 'com.google.android.libraries.places:places:4.1.0'

    implementation 'com.google.android.libraries.places:places:3.2.0'



    ////////Bioland/////////////

    implementation files('./libs/baseAdapter.aar')

//    implementation 'com.inuker.bluetooth:library:1.4.0'

    //
    implementation 'io.reactivex.rxjava2:rxjava:2.1.7'
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'

    //permission
//    implementation 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.2'

    //QMUI 依赖
    implementation 'com.qmuiteam:qmui:2.1.0'


    implementation 'com.github.GoodieBag:Pinview:v1.4'



    implementation 'com.google.firebase:firebase-messaging:23.1.2'


    implementation 'com.google.mlkit:face-detection:16.1.7'

    // CameraX
    def camerax_version = "1.3.0-alpha04"
    implementation "androidx.camera:camera-core:${camerax_version}"
    implementation "androidx.camera:camera-camera2:${camerax_version}"
    implementation "androidx.camera:camera-lifecycle:${camerax_version}"
    implementation "androidx.camera:camera-video:${camerax_version}"
    implementation "androidx.camera:camera-view:${camerax_version}"
    implementation "androidx.camera:camera-mlkit-vision:${camerax_version}"
    implementation "androidx.camera:camera-extensions:${camerax_version}"
    implementation 'com.google.android.gms:play-services-vision-common:19.1.3'

    implementation 'io.github.chaosleung:pinview:1.4.4'
//    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'io.github.vicmikhailau:MaskedEditText:5.0.2'

//    implementation  'com.google.android.play:asset-delivery'
//    implementation  'com.google.android.play:review:2.0.1'
//    implementation  'com.google.android.play:core-common:2.0.2'

}
